[symbol_servers]
breakpad = ["https://symbols.mozilla.org/try"]
windows = ["https://symbols.mozilla.org/try", "https://msdl.microsoft.com/download/symbols"]

[signature]
generator = "signify"

[cache]
directory = "symbolicate_cache"
size_limit_gb = 20
