---
trust-domain: "mozilla"
task-priority: low

taskgraph:
  register: 'local_taskgraph:register'
  cached-task-prefix: "mozilla.v2.crash-ping-ingest"
  repositories:
    crash_ping_ingest:
      name: "crash-ping-ingest"

workers:
  aliases:
    b-linux:
      provisioner: '{trust-domain}-{level}'
      implementation: docker-worker
      os: linux
      worker-type: '{alias}-gcp'
    images:
      provisioner: '{trust-domain}-{level}'
      implementation: docker-worker
      os: linux
      worker-type: '{alias}-gcp'
    t-linux:
      provisioner: '{trust-domain}-t'
      implementation: docker-worker
      os: linux
      worker-type: '{alias}-docker'
